### PR TITLE
Move everything to the root folder

### PR DESCRIPTION
**Pull request by desiderantes**

### CODE REVIEW

**Comment by ferdymercury** [comment]
Thanks for the suggestion!

- Please amend the README.md file, so that the instructions work with the new directory structure
- Please create an ignore-rev file to skip the big "move" commit from git blame

**Comment by desiderantes** [comment]
I see there's both a README and README.md file. Should I remove one of them? Symlink?

**Comment by ferdymercury** [comment]
> I see there's both a README and README.md file. Should I remove one of them? Symlink?

If you remove the symlink it is not rendered well on github as md. If we rename instead of symlink we have to check that make dist doesn't break or sth like that

**Comment by desiderantes** [comment]
> > I see there's both a README and README.md file. Should I remove one of them? Symlink?
> 
> If you remove the symlink it is not rendered well on github as md. If we rename instead of symlink we have to check that make dist doesn't break or sth like that

Then I'll leave such a change for a build system overhaul, whether it's CMake or Meson.

**Pull request merged**
